"use client";
import "./globals.css";

import Footer from "@/components/Footer";

import Header from "@/components/Header";
import { GoogleOAuthProvider } from "@react-oauth/google";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <GoogleOAuthProvider
          clientId={`${process.env.NEXT_PUBLIC_GOOGLE_API_TOKEN}`}
        >
          <Header />
          {children}
          <Footer />
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
